### ISSUE TITLE
TypeError: unsupported operand type(s) for +: 'method' and 'method'

### ISSUE THREAD

**Issue by eyildiz-ugoe** [nbarba/py3DRec#10]
Upon executing the given command in the README.md:

`python uncalibrated_rec.py --input_file=./example/features_poster.txt  --show`

I receive:

```
-------------------------------
 Uncalibrated 3D Reconstruction 

--------------------------------
Traceback (most recent call last):
  File "uncalibrated_rec.py", line 495, in <module>
    main(input_file=args.input_file, show=args.show)
  File "uncalibrated_rec.py", line 431, in main
    rec_engine = UncalibratedReconstruction(sequence.length, sequence.width, sequence.height)
  File "uncalibrated_rec.py", line 43, in __init__
    self._mm = (width + height) / 2
TypeError: unsupported operand type(s) for +: 'method' and 'method'
```

Any recommendations? (I use Python 3.8)

**Comment by vesuvisian** [comment]
There seem to be some bugs scattered in the code. Go into image_sequence.py and remove the feat_2d method and add the `@property` decorator to length, number_of_features, width, and height. Then, in model.py, change line 33 to `self._R, self._t = self.extract_rotation_translation(val)`. And line 49 of model.py can be `self._sequence_length=P.shape[2]`. Unfortunately in that same method, there a `K` matrix that comes out of no where.

**Comment by chaimaOues** [comment]
Hello, 
    PP=inv(K[:,:,i]).dot(P[:,:,i]);
NameError: name 'K' is not defined


how can i fixe this error please?

**Comment by chaimaOues** [comment]
Hello, I was able to solve the problem, it is necessary in uncalibrated-rec.py
in line 336
global K and after
 pass the variable K
in line 472
  recModel = RecModel(K)

and after in model.py
def __init__(self,K):
self.K = K
and in line 35
 self._R, self._t = self.extract_rotation_translation(val,self.K)

**Comment by chaimaOues** [comment]
i have this result(only two point and i used the data given with this code)
![Capture](https://user-images.githubusercontent.com/10595916/170047674-69b953d9-9372-4213-bb1c-83676daa8e30.JPG)
help please
