### ISSUE TITLE
AttributeError: can't set attribute

### ISSUE THREAD

**Issue by immkapoor** [nbarba/py3DRec#5]
I was trying to run the example code and encountered with following error. I haven't made any significant changes in the file.

Traceback (most recent call last):
  File "uncalibrated_rec.py", line 472, in <module>
    main(input_file=args.input_file,show=args.show)
  File "uncalibrated_rec.py", line 403, in main
    sequence=ImageSequence(input_file);
  File "/home/mk/Documents/3D Pose/py3DRec-master/image_sequence.py", line 10, in __init__
    self.load_features(filename)
  File "/home/mk/Documents/3D Pose/py3DRec-master/image_sequence.py", line 44, in load_features
    self.feat_2d=np.zeros(shape=[self._length,4,self._number_of_features])
AttributeError: can't set attribute

**Comment by elhadjmama** [comment]
I just replace in the functions feat_2d(self) and load_features( )  self.feat_2d by self._feat_2d.
